### ISSUE TITLE
Trigger from github comment

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/slurm-buildkite#13]
Would be nice to be able to trigger builds of specific steps from github comments: either via a specific job name,
```
@climabot run <jobname>
```
or specify a yml file in a codeblock

     @climabot run
    ```
    steps:
    - command: "mpiexec julia --project foo.jl"
    ```

(we could use something other than `@climabot` for this)

Would need to be careful to limit it to authorized users.
Might be able to use https://github.com/buildkite/trigger-pipeline-action

**Comment by jakebolewski** [comment]
I dont think we can do number 2 looking at the API, but number 1 is possible and seems better as the execution is not arbitrary (needs to go through review)

**Comment by ali-ramadhan** [comment]
This would be pretty useful! Unfortunately it looks like there's been an open issue about it on Buildkite for years: https://github.com/buildkite/feedback/issues/288

Guess it might have to go through https://github.com/buildkite/trigger-pipeline-action
