### ISSUE TITLE
add slurm job id to logs corresponding to sbatch submission to be able to track jobid <-> slurmjob id relationship

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/slurm-buildkite#17]
This is useful for checking if a particular buildkite job id successfully submitted experienced some failure on the slurm controller / squeue side of things for postmortem.

**Comment by simonbyrne** [comment]
I set it as the `jobid` agent tag, which is visible under the "Timeline" tab. The problem though is that you won't see it until the slurm job starts.

**Comment by simonbyrne** [comment]
See here:
https://github.com/CliMA/slurm-buildkite/blob/640960edaecff04da5b5591e965a652eaa0a5bcf/bin/slurmjob.sh#L12
We could change it to `slurm_jobid` to be more descriptive.

**Comment by jakebolewski** [comment]
that attaches to the agent, this would more be for the poll log output to make it easier to grep (by checking buildid, jobid, slurmjob id as in the deadlock senario the job was never scheduled to a live agent

it's printed to stderr by sbatch, so the info is there is just a little difficult to search for

**Comment by simonbyrne** [comment]
we could put it in the cron log (since it has access to all 3)

**Comment by simonbyrne** [comment]
If you use `sbatch --parsable` it returns just the slurm job id.
