### ISSUE TITLE
Cutting down on instantiation time

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/slurm-buildkite#30]
Currently we instantiate the whole Julia depot from scratch each time, and it takes about 10-15 minutes to set up everything. Of this, about 3 minutes is `Pkg.instantiate`, and 9 minutes is `Pkg.precompile`. 

There are two primary reasons for this setup:
1. Pkg operations still aren't completely atomic (i.e. we can get issues if multiple jobs try to write to modify depot files at the same time).
2. MPI.jl hardcodes needs to be hardcoded to a specific MPI implementation (at least until https://github.com/JuliaParallel/MPI.jl/pull/513 is in).

Following some discussion on the JuliaHPC call, and some experimentation, I think something like the following would be feasible:

1. We define a notion of "environments": each environment should load a fixed set of modules, set environment variables, etc
  - This should replace the case statement in https://github.com/CliMA/slurm-buildkite/blob/master/hooks/environment
  - For reproducibility, it ideally it should be a fixed version of everything, but we could probably allow some limited set of options, such as Julia versioning via an environment variable?

2. Each environment has associated with it a Julia depot that is restricted so that it can only be written once at a time. There are two ways I can think to do this:
  a. Use a Pid lock, such as [PkgLock.jl](https://github.com/simonbyrne/PkgLock.jl)
  b. Within a slurm `--dependency=singleton` job (this is based on job name)

3. Once this has been completed, we would push a build-specific depot path in front, so any Pkg operations (such as further precompilations or artifact downloads) would be limited to the build.

On the MPI issue, it does look like it is safe to use the CUDA MPI on non-CUDA nodes. The only annoying thing is that you get a warning, but that can be disabled via the `--mca opal_warn_on_missing_libcuda 0` option, or use environment variable (https://www.open-mpi.org/faq/?category=tuning#setting-mca-params suggests we should use `OMPI_MCA_opal_warn_on_missing_libcuda=0`)

**Comment by simonbyrne** [comment]
Alternatively to 2, one other suggestion would be to only allow writing to the build depot, but have a post-hook that would move any new precompile files back to the environment depot.

**Comment by jakebolewski** [comment]
I agree that we can cache the ENV in a better way (and do this on  one repo TC.jl), but we need to pre-compile the packages ahead of time for parallel (with MPI) and / or concurrent jobs.

**Comment by jakebolewski** [comment]
In every case where we relaxed some of these assumptions, the amount of required manual fixes increased.  I have not had to log in for months to fix things which is what the current situation is optimized for while trading off some fixed overhead.

**Comment by jakebolewski** [comment]
So I would advocate maybe being conservative for CI and not change much (because it works and is pretty robust).  If we want to change some of these settings we run maybe a fork applied against a different work queue.

**Comment by simonbyrne** [comment]
I agree. I was thinking we could add extra configs (so the existing ones would remain untouched), but if you would prefer to use a separate queue, that would be fine too.

**Comment by jakebolewski** [comment]
If you want to have a relatively dynamic job submission  pipeline then we'll need to programmatically render the job  yaml description, that is enough of a change that probably it would be good to start from scratch and crib where we can from the existing system.

**Comment by simonbyrne** [comment]
Good point. Lets not break prod.
